# GitHub Actions 工作流程名稱
name: Build and Release StellarNeo

# 工作流程觸發條件
on:
  # 允許手動從 Actions 頁面觸發
  workflow_dispatch:
  # 當建立一個符合 'v*.*.*' 格式的標籤時觸發
  push:
    tags:
      - 'v*.*.*'

# 工作流程執行的任務
jobs:
  # 'create_release' 任務：建立一個 GitHub Release
  # 這個任務會先執行，因為 build 任務需要它
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    # 修正 1: 增加 'permissions' 以授予建立 Release 的權限
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release of StellarNeo.
            See the commit history for details.
          draft: false
          prerelease: false

  # 'build' 任務：在不同作業系統上打包應用程式
  build:
    # 修正 2: 聲明此任務需要等待 'create_release' 任務完成
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 步驟 1: 簽出 (Checkout) 您的專案程式碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步驟 2: 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 步驟 3: 安裝依賴套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 步驟 4: (僅限 Linux) 安裝 Qt 相關的系統依賴
      # 修正 3: 更新適用於新版 Ubuntu 的依賴套件
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 libxcb-cursor0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0

      # 步驟 5: 使用 PyInstaller 進行打包
      - name: Build with PyInstaller
        run: pyinstaller StellarNeo.spec

      # 步驟 6: 準備要上傳的檔案 (壓縮)
      - name: Prepare artifact for release
        shell: bash
        run: |
          # 獲取版本號 (從標籤名稱)
          VERSION=${{ github.ref_name }}
          
          # 設定輸出目錄和檔案名稱
          if [ "${{ runner.os }}" == "Windows" ]; then
            ARTIFACT_NAME="StellarNeo-${VERSION}-windows-x64"
            7z a -tzip "${ARTIFACT_NAME}.zip" "./dist/StellarNeo/*"
            echo "ASSET=${ARTIFACT_NAME}.zip" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" == "macOS" ]; then
            ARTIFACT_NAME="StellarNeo-${VERSION}-macos-x64"
            # On macOS, the default 'tar' from PyInstaller is inside the .app bundle
            # We need to make sure we are packaging the .app directory itself
            mv dist/StellarNeo.app dist/StellarNeo
            tar -czf "${ARTIFACT_NAME}.tar.gz" -C "./dist" "StellarNeo"
            echo "ASSET=${ARTIFACT_NAME}.tar.gz" >> $GITHUB_ENV
          else # Linux
            ARTIFACT_NAME="StellarNeo-${VERSION}-linux-x64"
            tar -czf "${ARTIFACT_NAME}.tar.gz" -C "./dist" "StellarNeo"
            echo "ASSET=${ARTIFACT_NAME}.tar.gz" >> $GITHUB_ENV
          fi

      # 步驟 7: 上傳打包好的檔案作為工作流程產物 (Artifact)
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream